-- Insertar productos
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY) VALUES ('Producto 1', 'Descripción del Producto 1', 10.99, 'Categoría A');
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY) VALUES ('Producto 2', 'Descripción del Producto 2', 15.49, 'Categoría B');
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY) VALUES ('Producto 3', 'Descripción del Producto 3', 23.00, 'Categoría A');

-- Insertar detalles para Producto 1
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Color', 'Rojo', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Tamaño', 'Mediano', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Peso', '500g', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Material', 'Plástico', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Garantía', '2 años', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Origen', 'China', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Durabilidad', '5 años', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Marca', 'Marca A', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Compatibilidad', 'Universal', 1);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Uso', 'Interior', 1);

-- Insertar detalles para Producto 2
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Color', 'Azul', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Tamaño', 'Grande', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Peso', '1kg', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Material', 'Metal', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Garantía', '1 año', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Origen', 'USA', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Durabilidad', '10 años', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Marca', 'Marca B', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Compatibilidad', 'Específico', 2);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Uso', 'Exterior', 2);

-- Insertar detalles para Producto 3
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Color', 'Verde', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Tamaño', 'Pequeño', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Peso', '300g', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Material', 'Vidrio', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Garantía', '3 años', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Origen', 'Alemania', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Durabilidad', '3 años', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Marca', 'Marca C', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Compatibilidad', 'Exclusivo', 3);
INSERT INTO PRODUCT_DETAIL (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRODUCT_ID) VALUES ('Uso', 'Multifuncional', 3);
