CREATE TABLE PRODUCT (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL,
    CATEGORY VARCHAR(255)
);

CREATE TABLE PRODUCT_DETAIL (
    PRODUCT_DETAIL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ATTRIBUTE_NAME VARCHAR(255),
    ATTRIBUTE_VALUE VARCHAR(255),
    PRODUCT_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

