CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE NUMERIC(10, 2),
    CATEGORY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUCT_DETAIL (
    PRODUCT_DETAIL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATTRIBUTE_NAME VARCHAR(255),
    ATTRIBUTE_VALUE VARCHAR(255),
    PRODUCT_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
