name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set version based on run number
        id: version
        run: |
          TAG_NAME="v1.${{ github.run_number }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION=${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Update version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "Update version to ${{ env.VERSION }}"
          git push origin master

      - name: Build with Maven
        run: mvn clean package

      - name: Verify JAR Build
        run: file target/api-${{ env.VERSION }}.jar

      - name: Create GitHub Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Create GitHub Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: target/api-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker Build Context
        run: mv target/api-${{ env.VERSION }}.jar ./api.jar  # Mueve el JAR al contexto de construcción de Docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/api:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/api:latest .
          docker push ghcr.io/${{ github.repository_owner }}/api:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/api:latest
